apiVersion: v1
kind: ConfigMap
metadata:
  name: sspp-config
  namespace: sspp-dev
data:
  NODE_ENV: "development"
  API_PREFIX: "api/v1"
  QUEUE_NAME: "sales-events"
  QUEUE_CONCURRENCY: "5"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "sales_signals"
  ELASTICSEARCH_NODE: "http://elasticsearch-service:9200"
