apiVersion: v1
kind: Namespace
metadata:
  name: sspp-dev
  labels:
    name: sspp-dev
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: sspp-prod
  labels:
    name: sspp-prod
    environment: production
