name: sspp-worker
replicaCount: 2

image:
  repository: davidbrown77/sspp-worker
  tag: latest
  pullPolicy: IfNotPresent

redis:
  url: "redis://redis:6379"

database:
  url: "postgresql://user:pass@postgres:5432/sspp"

elasticsearch:
  url: "http://elasticsearch:9200"

queueName: "sales-events"

resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

env: {}

nodeSelector: {}

tolerations: []

affinity: {}
