apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sspp-dev

resources:
  - ../../base

patchesStrategicMerge:
  - patch-replicas.yaml

configMapGenerator:
  - name: sspp-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug

commonLabels:
  environment: dev
