apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sspp-staging

resources:
  - ../../base

patchesStrategicMerge:
  - patch-replicas.yaml

configMapGenerator:
  - name: sspp-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info

commonLabels:
  environment: staging
