apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sspp-prod

resources:
  - ../../base
  - hpa.yaml

patchesStrategicMerge:
  - patch-replicas.yaml

images:
  - name: davidbrown77/sspp-api
    newTag: latest
  - name: davidbrown77/sspp-worker
    newTag: latest

configMapGenerator:
  - name: sspp-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info

commonLabels:
  environment: production
