apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sspp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:DaviesBrown/sspp.git
    targetRevision: HEAD
    path: infrastructure/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sspp-dev